# Generated by Django 4.2.7 on 2023-11-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='tour_name',
            field=models.CharField(default=1, max_length=128, verbose_name='Имя тура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='tour_price',
            field=models.CharField(default=1, max_length=128, verbose_name='Цена тура'),
            preserve_default=False,
        ),
    ]
